### ISSUE TITLE
error: Unexpected data encountered in config data

### ISSUE THREAD

**Issue by darylknight** [verbb/hyper#15]
### Describe the bug

I'm working on my Boilerplate. I've replaced Typed Link Field with Hyper, then trying to run `./craft project-cofig/rebuild` and running into this error, even after completely deleting all link fields, deleting the database, re-installing and adding new fields.

```
./craft project-config/rebuild
Rebuilding the project config from the current state ... error: Unexpected data encountered in config data
```

I can replicate this by deleting all Hyper fields, then the command runs fine. If I create a hyper field then try to run it again, I get this error message.

Here's the full log file:

```
2023-02-22 09:46:50 [console.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=127.0.0.1;dbname=boilerplate;port=3306 {"memory":11334008} 
2023-02-22 09:46:50 [console.INFO] [wbrowar\adminbar\AdminBar::init] Admin Bar plugin loaded {"memory":15575600} 
2023-02-22 09:46:50 [console.INFO] [mmikkel\retcon\Retcon::init] Retcon plugin loaded {"memory":21086560} 
2023-02-22 09:46:50 [console.INFO] [nystudio107\seomatic\Seomatic::init] SEOmatic plugin loaded {"memory":21671576} 
2023-02-22 09:46:50 [console.INFO] [nystudio107\twigpack\Twigpack::init] Twigpack plugin loaded {"memory":21930800} 
2023-02-22 09:46:50 [console.INFO] [application] Unexpected data encountered in config data - verbb\hyper\links\Asset Object
(
    [revisionCreatorId] => 
    [revisionNotes] => 
    [id] => 
    [tempId] => 
    [draftId] => 
    [revisionId] => 
    [isProvisionalDraft] => 
    [uid] => 
    [siteSettingsId] => 
    [fieldLayoutId] => 
    [structureId] => 
    [contentId] => 
    [enabled] => 
    [archived] => 
    [siteId] => 1
    [title] => 
    [slug] => 
    [uri] => 
    [dateCreated] => 
    [dateUpdated] => 
    [dateLastMerged] => 
    [dateDeleted] => 
    [root] => 
    [lft] => 
    [rgt] => 
    [level] => 
    [searchScore] => 
    [trashed] => 
    [awaitingFieldValues] => 
    [propagating] => 
    [propagateAll] => 
    [newSiteIds] => Array
        (
        )

    [isNewForSite] => 
    [resaving] => 
    [duplicateOf] => 
    [firstSave] => 
    [mergingCanonicalChanges] => 
    [updatingFromDerivative] => 
    [previewing] => 
    [hardDelete] => 
    [label] => Asset
    [handle] => default-verbb-hyper-links-asset
    [isCustom] => 
    [layoutUid] => 3370a07f-187f-41a6-9e2f-51e370d9aad2
    [layoutConfig] => Array
        (
            [uid] => eb37a091-c0bd-46cc-abb6-c544f6a9f590
            [tabs] => Array
                (
                    [0] => Array
                        (
                            [name] => Content
                            [uid] => f94eb625-3f4c-4e36-bc98-e6f928768e46
                            [elements] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => verbb\hyper\fieldlayoutelements\LinkField
                                            [attribute] => linkValue
                                            [mandatory] => 1
                                            [autocomplete] => 
                                            [autofocus] => 
                                            [autocorrect] => 1
                                            [autocapitalize] => 1
                                            [disabled] => 
                                            [readonly] => 
                                            [requirable] => 
                                            [translatable] => 
                                            [required] => 
                                            [width] => 50
                                            [uid] => ffe5bc2c-a642-4c3b-b235-cfdfdab36a0a
                                        )

                                    [1] => Array
                                        (
                                            [type] => verbb\hyper\fieldlayoutelements\LinkTextField
                                            [attribute] => linkText
                                            [requirable] => 1
                                            [autocomplete] => 
                                            [autofocus] => 
                                            [autocorrect] => 1
                                            [autocapitalize] => 1
                                            [disabled] => 
                                            [readonly] => 
                                            [placeholder] => e.g. Read more
                                            [mandatory] => 
                                            [translatable] => 
                                            [required] => 
                                            [width] => 50
                                            [uid] => 4bb9dfc9-bd18-4100-b8ce-e4b6549e707d
                                        )

                                )

                        )

                    [1] => Array
                        (
                            [name] => Advanced
                            [uid] => 5abb2231-f306-43db-a9e3-4ff9826937b8
                            [elements] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => verbb\hyper\fieldlayoutelements\LinkTitleField
                                            [attribute] => linkTitle
                                            [requirable] => 1
                                            [autocomplete] => 
                                            [autofocus] => 
                                            [autocorrect] => 1
                                            [autocapitalize] => 1
                                            [disabled] => 
                                            [readonly] => 
                                            [mandatory] => 
                                            [translatable] => 
                                            [required] => 
                                            [width] => 100
                                            [uid] => eb4f12eb-189c-4812-8060-1cc037c89b5a
                                        )

                                    [1] => Array
                                        (
                                            [type] => verbb\hyper\fieldlayoutelements\ClassesField
                                            [attribute] => classes
                                            [requirable] => 1
                                            [autocomplete] => 
                                            [autofocus] => 
                                            [autocorrect] => 1
                                            [autocapitalize] => 1
                                            [disabled] => 
                                            [readonly] => 
                                            [mandatory] => 
                                            [translatable] => 
                                            [required] => 
                                            [width] => 100
                                            [uid] => a00a5a68-7da3-4115-9f9e-c09f19339181
                                        )

                                    [2] => Array
                                        (
                                            [type] => verbb\hyper\fieldlayoutelements\CustomAttributesField
                                            [attribute] => customAttributes
                                            [requirable] => 1
                                            [mandatory] => 
                                            [translatable] => 
                                            [required] => 
                                            [width] => 100
                                            [uid] => 06443cca-c5b7-41f8-98fa-33f1f19bb33d
                                        )

                                )

                        )

                )

        )

    [newWindow] => 
    [linkValue] => 
    [linkText] => 
    [ariaLabel] => 
    [urlSuffix] => 
    [linkTitle] => 
    [classes] => 
    [customAttributes] => Array
        (
        )

    [fields] => Array
        (
        )

    [field] => 
    [isFieldRequired] => 
    [_fieldLayout] => 
    [linkSiteId] => 
    [sources] => *
    [selectionLabel] => 
)
 {"memory":30882208} 
2023-02-22 09:46:50 [console.ERROR] [yii\base\InvalidConfigException] yii\base\InvalidConfigException: Unexpected data encountered in config data in /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php:276
Stack trace:
#0 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(248): craft\helpers\ProjectConfig::_cleanupConfigValue(Object(verbb\hyper\links\Asset))
#1 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(304): craft\helpers\ProjectConfig::cleanupConfig(Array)
#2 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(248): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
#3 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(304): craft\helpers\ProjectConfig::cleanupConfig(Array)
#4 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(248): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
#5 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(304): craft\helpers\ProjectConfig::cleanupConfig(Array)
#6 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(248): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
#7 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/services/ProjectConfig.php(486): craft\helpers\ProjectConfig::cleanupConfig(Array)
#8 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/services/ProjectConfig.php(475): craft\services\ProjectConfig->_setInternal('fields', Array, 'Project config ...', false, true)
#9 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/services/ProjectConfig.php(1199): craft\services\ProjectConfig->set('fields', Array, 'Project config ...', false, true)
#10 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(419): craft\services\ProjectConfig->rebuild()
#11 [internal function]: craft\console\controllers\ProjectConfigController->actionRebuild()
#12 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('rebuild', Array)
#15 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/console/Controller.php(227): yii\console\Controller->runAction('rebuild', Array)
#16 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('rebuild', Array)
#17 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#18 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('project-config/...', Array)
#19 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#20 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#22 /Users/darylknight/Sites/boilerplate-tailwind/craft(13): yii\base\Application->run()
#23 {main} {"memory":30744936,"exception":"[object] (yii\\base\\InvalidConfigException(code: 0): Unexpected data encountered in config data at /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php:276)"} 
2023-02-22 09:46:50 [console.INFO] [application] Request context:
$_GET = []

$_POST = []

$_COOKIE = []

$_FILES = []

$_SERVER = [
    'TERM_SESSION_ID' => 'w0t0p1:B5E312F2-519F-4CEE-A03C-5A7043241605'
    'SSH_AUTH_SOCK' => '/private/tmp/com.apple.launchd.9LqPRG0O6z/Listeners'
    'LC_TERMINAL_VERSION' => '3.4.19'
    'COLORFGBG' => '15;0'
    'ITERM_PROFILE' => 'Default'
    'XPC_FLAGS' => '0x0'
    'PWD' => '/Users/darylknight/Sites/boilerplate-tailwind'
    'SHELL' => '/bin/zsh'
    '__CFBundleIdentifier' => 'com.googlecode.iterm2'
    'SECURITYSESSIONID' => '186a6'
    'LC_CTYPE' => 'UTF-8'
    'TERM_PROGRAM_VERSION' => '3.4.19'
    'TERM_PROGRAM' => 'iTerm.app'
    'PATH' => '/usr/local/opt/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin'
    'LC_TERMINAL' => 'iTerm2'
    'COLORTERM' => 'truecolor'
    'COMMAND_MODE' => 'unix2003'
    'TERM' => 'xterm-256color'
    'HOME' => '/Users/darylknight'
    'TMPDIR' => '/var/folders/md/hdlfr3js0998rtnjbxws99mc0000gn/T/'
    'USER' => 'darylknight'
    'XPC_SERVICE_NAME' => '0'
    'LOGNAME' => 'darylknight'
    'LaunchInstanceID' => '6AADE8CD-D147-4B23-82FB-C4C9C95D748F'
    'ITERM_SESSION_ID' => 'w0t0p1:B5E312F2-519F-4CEE-A03C-5A7043241605'
    '__CF_USER_TEXT_ENCODING' => '0x1F5:0x0:0x2'
    'SHLVL' => '1'
    'OLDPWD' => '/Users/darylknight/Sites'
    'P9K_TTY' => 'old'
    '_P9K_TTY' => '/dev/ttys001'
    'ZSH' => '/Users/darylknight/.oh-my-zsh'
    'PAGER' => 'less'
    'LESS' => '-R'
    'LSCOLORS' => 'Gxfxcxdxbxegedabagacad'
    'P9K_SSH' => '0'
    '_' => '/Users/darylknight/Sites/boilerplate-tailwind/./craft'
    'PHP_SELF' => './craft'
    'SCRIPT_NAME' => './craft'
    'SCRIPT_FILENAME' => './craft'
    'PATH_TRANSLATED' => './craft'
    'DOCUMENT_ROOT' => ''
    'REQUEST_TIME_FLOAT' => 1677059210.0474
    'REQUEST_TIME' => 1677059210
    'argv' => [
        0 => './craft'
        1 => 'project-config/rebuild'
    ]
    'argc' => 2
    'ENVIRONMENT' => 'dev'
    'CRAFT_APP_ID' => 'CraftCMS--e59bcdc5-2b17-4162-90b5-e76c463743b8'
    'CRAFT_SECURITY_KEY' => '••••••••••••••••••••••••••••••••'
    'SYSTEM_STATUS' => 'on'
    'CRAFT_DB_DRIVER' => 'mysql'
    'CRAFT_DB_SERVER' => '127.0.0.1'
    'CRAFT_DB_PORT' => '3306'
    'CRAFT_DB_DATABASE' => 'boilerplate'
    'CRAFT_DB_USER' => 'root'
    'CRAFT_DB_PASSWORD' => '••••'
    'CRAFT_DB_SCHEMA' => ''
    'CRAFT_DB_TABLE_PREFIX' => ''
    'CP_TRIGGER' => 'control'
    'PRIMARY_SITE_URL' => 'http://boilerplate-tailwind.test'
    'BASE_PATH' => '/Users/darylknight/Sites/boilerplate-tailwind/public'
    'PLUGIN_FORMIE' => '2D5N-X4UA-FESQ-R3GH-OELV-J8AW'
    'PLUGIN_HYPER' => 'LJWI-7IUW-H6LN-QDYG-4Q5E-GY00'
    'PLUGIN_SEOMATIC' => 'C4EO-E6AN-JHSP-AL12-OIXG-JRMH'
    'EMAIL_SYSTEM_ADDRESS' => 'daryl@codeknight.co.uk'
    'EMAIL_SENDER' => 'CodeKnight'
    'EMAIL_HOST' => 'smtp.mailtrap.io'
    'EMAIL_PORT' => '465'
    'EMAIL_AUTH' => 'true'
    'EMAIL_USERNAME' => '7c6f322484e136'
    'EMAIL_PASSWORD' => '••••••••••••••'
    'FORMIE_CAPTCHA_RECAPTCHA' => 'off'
    'FORMIE_CAPTCHA_HCAPTCHA' => 'off'
    'FORMIE_CAPTCHA_DUPLICATE' => 'on'
    'FORMIE_CAPTCHA_HONEYPOT' => 'on'
    'FORMIE_CAPTCHA_JAVASCRIPT' => 'on'
]  
2023-02-22 09:48:19 [console.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=127.0.0.1;dbname=boilerplate;port=3306 {"memory":11334008} 
2023-02-22 09:48:19 [console.INFO] [wbrowar\adminbar\AdminBar::init] Admin Bar plugin loaded {"memory":15557936} 
2023-02-22 09:48:19 [console.INFO] [mmikkel\retcon\Retcon::init] Retcon plugin loaded {"memory":21068896} 
2023-02-22 09:48:19 [console.INFO] [nystudio107\seomatic\Seomatic::init] SEOmatic plugin loaded {"memory":21653912} 
2023-02-22 09:48:19 [console.INFO] [nystudio107\twigpack\Twigpack::init] Twigpack plugin loaded {"memory":21913136} 
2023-02-22 09:48:19 [console.INFO] [application] Unexpected data encountered in config data - verbb\hyper\links\Asset Object
(
    [revisionCreatorId] => 
    [revisionNotes] => 
    [id] => 
    [tempId] => 
    [draftId] => 
    [revisionId] => 
    [isProvisionalDraft] => 
    [uid] => 
    [siteSettingsId] => 
    [fieldLayoutId] => 
    [structureId] => 
    [contentId] => 
    [enabled] => 
    [archived] => 
    [siteId] => 1
    [title] => 
    [slug] => 
    [uri] => 
    [dateCreated] => 
    [dateUpdated] => 
    [dateLastMerged] => 
    [dateDeleted] => 
    [root] => 
    [lft] => 
    [rgt] => 
    [level] => 
    [searchScore] => 
    [trashed] => 
    [awaitingFieldValues] => 
    [propagating] => 
    [propagateAll] => 
    [newSiteIds] => Array
        (
        )

    [isNewForSite] => 
    [resaving] => 
    [duplicateOf] => 
    [firstSave] => 
    [mergingCanonicalChanges] => 
    [updatingFromDerivative] => 
    [previewing] => 
    [hardDelete] => 
    [label] => Asset
    [handle] => default-verbb-hyper-links-asset
    [isCustom] => 
    [layoutUid] => 3370a07f-187f-41a6-9e2f-51e370d9aad2
    [layoutConfig] => Array
        (
            [uid] => eb37a091-c0bd-46cc-abb6-c544f6a9f590
            [tabs] => Array
                (
                    [0] => Array
                        (
                            [name] => Content
                            [uid] => f94eb625-3f4c-4e36-bc98-e6f928768e46
                            [elements] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => verbb\hyper\fieldlayoutelements\LinkField
                                            [attribute] => linkValue
                                            [mandatory] => 1
                                            [autocomplete] => 
                                            [autofocus] => 
                                            [autocorrect] => 1
                                            [autocapitalize] => 1
                                            [disabled] => 
                                            [readonly] => 
                                            [requirable] => 
                                            [translatable] => 
                                            [required] => 
                                            [width] => 50
                                            [uid] => ffe5bc2c-a642-4c3b-b235-cfdfdab36a0a
                                        )

                                    [1] => Array
                                        (
                                            [type] => verbb\hyper\fieldlayoutelements\LinkTextField
                                            [attribute] => linkText
                                            [requirable] => 1
                                            [autocomplete] => 
                                            [autofocus] => 
                                            [autocorrect] => 1
                                            [autocapitalize] => 1
                                            [disabled] => 
                                            [readonly] => 
                                            [placeholder] => e.g. Read more
                                            [mandatory] => 
                                            [translatable] => 
                                            [required] => 
                                            [width] => 50
                                            [uid] => 4bb9dfc9-bd18-4100-b8ce-e4b6549e707d
                                        )

                                )

                        )

                    [1] => Array
                        (
                            [name] => Advanced
                            [uid] => 5abb2231-f306-43db-a9e3-4ff9826937b8
                            [elements] => Array
                                (
                                    [0] => Array
                                        (
                                            [type] => verbb\hyper\fieldlayoutelements\LinkTitleField
                                            [attribute] => linkTitle
                                            [requirable] => 1
                                            [autocomplete] => 
                                            [autofocus] => 
                                            [autocorrect] => 1
                                            [autocapitalize] => 1
                                            [disabled] => 
                                            [readonly] => 
                                            [mandatory] => 
                                            [translatable] => 
                                            [required] => 
                                            [width] => 100
                                            [uid] => eb4f12eb-189c-4812-8060-1cc037c89b5a
                                        )

                                    [1] => Array
                                        (
                                            [type] => verbb\hyper\fieldlayoutelements\ClassesField
                                            [attribute] => classes
                                            [requirable] => 1
                                            [autocomplete] => 
                                            [autofocus] => 
                                            [autocorrect] => 1
                                            [autocapitalize] => 1
                                            [disabled] => 
                                            [readonly] => 
                                            [mandatory] => 
                                            [translatable] => 
                                            [required] => 
                                            [width] => 100
                                            [uid] => a00a5a68-7da3-4115-9f9e-c09f19339181
                                        )

                                    [2] => Array
                                        (
                                            [type] => verbb\hyper\fieldlayoutelements\CustomAttributesField
                                            [attribute] => customAttributes
                                            [requirable] => 1
                                            [mandatory] => 
                                            [translatable] => 
                                            [required] => 
                                            [width] => 100
                                            [uid] => 06443cca-c5b7-41f8-98fa-33f1f19bb33d
                                        )

                                )

                        )

                )

        )

    [newWindow] => 
    [linkValue] => 
    [linkText] => 
    [ariaLabel] => 
    [urlSuffix] => 
    [linkTitle] => 
    [classes] => 
    [customAttributes] => Array
        (
        )

    [fields] => Array
        (
        )

    [field] => 
    [isFieldRequired] => 
    [_fieldLayout] => 
    [linkSiteId] => 
    [sources] => *
    [selectionLabel] => 
)
 {"memory":30824912} 
2023-02-22 09:48:19 [console.ERROR] [yii\base\InvalidConfigException] yii\base\InvalidConfigException: Unexpected data encountered in config data in /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php:276
Stack trace:
#0 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(248): craft\helpers\ProjectConfig::_cleanupConfigValue(Object(verbb\hyper\links\Asset))
#1 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(304): craft\helpers\ProjectConfig::cleanupConfig(Array)
#2 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(248): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
#3 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(304): craft\helpers\ProjectConfig::cleanupConfig(Array)
#4 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(248): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
#5 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(304): craft\helpers\ProjectConfig::cleanupConfig(Array)
#6 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php(248): craft\helpers\ProjectConfig::_cleanupConfigValue(Array)
#7 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/services/ProjectConfig.php(486): craft\helpers\ProjectConfig::cleanupConfig(Array)
#8 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/services/ProjectConfig.php(475): craft\services\ProjectConfig->_setInternal('fields', Array, 'Project config ...', false, true)
#9 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/services/ProjectConfig.php(1199): craft\services\ProjectConfig->set('fields', Array, 'Project config ...', false, true)
#10 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(419): craft\services\ProjectConfig->rebuild()
#11 [internal function]: craft\console\controllers\ProjectConfigController->actionRebuild()
#12 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('rebuild', Array)
#15 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/console/Controller.php(227): yii\console\Controller->runAction('rebuild', Array)
#16 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('rebuild', Array)
#17 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#18 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('project-config/...', Array)
#19 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#20 /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /Users/darylknight/Sites/boilerplate-tailwind/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#22 /Users/darylknight/Sites/boilerplate-tailwind/craft(13): yii\base\Application->run()
#23 {main} {"memory":30700120,"exception":"[object] (yii\\base\\InvalidConfigException(code: 0): Unexpected data encountered in config data at /Users/darylknight/Sites/boilerplate-tailwind/vendor/craftcms/cms/src/helpers/ProjectConfig.php:276)"} 
2023-02-22 09:48:19 [console.INFO] [application] Request context:
$_GET = []

$_POST = []

$_COOKIE = []

$_FILES = []

$_SERVER = [
    'TERM_SESSION_ID' => 'w0t0p1:B5E312F2-519F-4CEE-A03C-5A7043241605'
    'SSH_AUTH_SOCK' => '/private/tmp/com.apple.launchd.9LqPRG0O6z/Listeners'
    'LC_TERMINAL_VERSION' => '3.4.19'
    'COLORFGBG' => '15;0'
    'ITERM_PROFILE' => 'Default'
    'XPC_FLAGS' => '0x0'
    'PWD' => '/Users/darylknight/Sites/boilerplate-tailwind'
    'SHELL' => '/bin/zsh'
    '__CFBundleIdentifier' => 'com.googlecode.iterm2'
    'SECURITYSESSIONID' => '186a6'
    'LC_CTYPE' => 'UTF-8'
    'TERM_PROGRAM_VERSION' => '3.4.19'
    'TERM_PROGRAM' => 'iTerm.app'
    'PATH' => '/usr/local/opt/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin'
    'LC_TERMINAL' => 'iTerm2'
    'COLORTERM' => 'truecolor'
    'COMMAND_MODE' => 'unix2003'
    'TERM' => 'xterm-256color'
    'HOME' => '/Users/darylknight'
    'TMPDIR' => '/var/folders/md/hdlfr3js0998rtnjbxws99mc0000gn/T/'
    'USER' => 'darylknight'
    'XPC_SERVICE_NAME' => '0'
    'LOGNAME' => 'darylknight'
    'LaunchInstanceID' => '6AADE8CD-D147-4B23-82FB-C4C9C95D748F'
    'ITERM_SESSION_ID' => 'w0t0p1:B5E312F2-519F-4CEE-A03C-5A7043241605'
    '__CF_USER_TEXT_ENCODING' => '0x1F5:0x0:0x2'
    'SHLVL' => '1'
    'OLDPWD' => '/Users/darylknight/Sites'
    'P9K_TTY' => 'old'
    '_P9K_TTY' => '/dev/ttys001'
    'ZSH' => '/Users/darylknight/.oh-my-zsh'
    'PAGER' => 'less'
    'LESS' => '-R'
    'LSCOLORS' => 'Gxfxcxdxbxegedabagacad'
    'P9K_SSH' => '0'
    '_' => '/Users/darylknight/Sites/boilerplate-tailwind/./craft'
    'PHP_SELF' => './craft'
    'SCRIPT_NAME' => './craft'
    'SCRIPT_FILENAME' => './craft'
    'PATH_TRANSLATED' => './craft'
    'DOCUMENT_ROOT' => ''
    'REQUEST_TIME_FLOAT' => 1677059298.5946
    'REQUEST_TIME' => 1677059298
    'argv' => [
        0 => './craft'
        1 => 'project-config/rebuild'
    ]
    'argc' => 2
    'ENVIRONMENT' => 'dev'
    'CRAFT_APP_ID' => '••••••••••••••••••••••••••••••••'
    'CRAFT_SECURITY_KEY' => '••••••••••••••••••••••••••••••••'
    'SYSTEM_STATUS' => 'on'
    'CRAFT_DB_DRIVER' => 'mysql'
    'CRAFT_DB_SERVER' => '127.0.0.1'
    'CRAFT_DB_PORT' => '3306'
    'CRAFT_DB_DATABASE' => 'boilerplate'
    'CRAFT_DB_USER' => 'root'
    'CRAFT_DB_PASSWORD' => '••••'
    'CRAFT_DB_SCHEMA' => ''
    'CRAFT_DB_TABLE_PREFIX' => ''
    'CP_TRIGGER' => 'control'
    'PRIMARY_SITE_URL' => 'http://boilerplate-tailwind.test'
    'BASE_PATH' => '/Users/darylknight/Sites/boilerplate-tailwind/public'
    'PLUGIN_FORMIE' => '••••••••••••••'
    'PLUGIN_HYPER' => '••••••••••••••'
    'PLUGIN_SEOMATIC' => '••••••••••••••'
    'EMAIL_SYSTEM_ADDRESS' => '••••••••••••••'
    'EMAIL_SENDER' => '••••••••••••••'
    'EMAIL_HOST' => 'smtp.mailtrap.io'
    'EMAIL_PORT' => '465'
    'EMAIL_AUTH' => 'true'
    'EMAIL_USERNAME' => '••••••••••••••'
    'EMAIL_PASSWORD' => '••••••••••••••'
    'FORMIE_CAPTCHA_RECAPTCHA' => 'off'
    'FORMIE_CAPTCHA_HCAPTCHA' => 'off'
    'FORMIE_CAPTCHA_DUPLICATE' => 'on'
    'FORMIE_CAPTCHA_HONEYPOT' => 'on'
    'FORMIE_CAPTCHA_JAVASCRIPT' => 'on'
]  
```

### Steps to reproduce

1. Create a Hyper field
2. Run `./craft project-config/rebuild`

### Craft CMS version

4.3.10

### Plugin version

1.0.4

### Multi-site?

No

**Comment by engram-design** [comment]
Strange, I've never seen the `Unexpected data encountered in config data`, but you're right, that's triggered on a `rebuild`.

Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.4"`

**Comment by darylknight** [comment]
Yeah it's a weird one. Thank you!

**Comment by darylknight** [comment]
This didn't fix the issue:

![image](https://user-images.githubusercontent.com/1250017/220614262-ef5158eb-371a-4eb7-9fa8-b679ca8d6865.png)

**Comment by engram-design** [comment]
If you'd like to give that another go now?

**Comment by darylknight** [comment]
Yep, that did it! Thank you

**Comment by engram-design** [comment]
Updated in [1.0.5](https://github.com/verbb/hyper/releases/tag/1.0.5)
