### ISSUE TITLE
Permanent "unsaved changes"

### ISSUE THREAD

**Issue by WebitMaxime** [verbb/hyper#198]
### Describe the bug

If an entry has an Hyper link field, it will be flagged as a new revision every time you open or save the entry.

### Steps to reproduce

1. Add an Hyper link field inside a Matrix field
2. Add the field in an Entry
3. Save/refresh/whatever

### Craft CMS version

5.4.5.1

### Plugin version

2.0.5

### Additional context

The Hyper field is being used as a "button" field inside a Matrix in order to be a "button group" field.
The matrix is being used inside a Neo field separated in multiple layout blocks (ie. media/text layout, accordions layout, text only layout, etc.)

**Comment by engram-design** [comment]
It's a known issue, we're working on it, and should be fixed in Craft 5.5 and Hyper 2.1. See https://github.com/verbb/hyper/issues/189

**Comment by frederik-station** [comment]
@engram-design I'm still experiencing this issue but weirdly enough only when the link text contains any of the characters ä, ö or ü. I'm using the Hyper field inside a Matrix field inside a Neo field.

Craft: 5.5.6.1
Hyper: 2.2.1

**Comment by engram-design** [comment]
Can't seem to replicate that with special characters, sorry! Can you let me know if it's a specific link type (or any), and if you also see this behaviour in a standalone, top-level Hyper field (so no Matrix or Neo)

**Comment by frederik-station** [comment]
It occurs with any relationship type link (tested with Entry, Asset and Product) and also with top-level Hyper fields.
<img width="763" alt="image" src="https://github.com/user-attachments/assets/37a0dcc2-fba4-4c7d-b7fe-6e4e7f6e77ca" />

The notice appears when I switch to another tab:
<img width="424" alt="image" src="https://github.com/user-attachments/assets/61cd203c-5f55-40e2-a6e6-26d2756452db" />

**Comment by engram-design** [comment]
Hmm, thanks for confirming, I'll continue to try and replicate that!

**Comment by frederik-station** [comment]
@engram-design I no longer have this issue after updating to Hyper 2.2.2

**Comment by ryanleichty** [comment]
We're on Hyper 2.2.7 and Craft 5.8.14 and this is still an issue

<img width="3680" height="2384" alt="Image" src="https://github.com/user-attachments/assets/a0aba744-bf45-4686-9068-a987bf0aae80" />

**Comment by engram-design** [comment]
@ryanleichty Out of interest, does this happen when you're _not_ in the slide-out editor interface? From memory, there's some complications/handling for that, that's different to when it's outside the slide-out.

**Comment by engram-design** [comment]
Should be fixed in [2.3.0](https://github.com/verbb/hyper/releases/tag/2.3.0).
