### ISSUE TITLE
Nesting Hyper fields

### ISSUE THREAD

**Issue by stevendierick** [verbb/hyper#66]
### Describe the bug

There seem to be a couple of issues when nesting Hyper fields:

- When you add a link to a nested Hyper then only the first link will work. When you add a second, third, fourth, etc. link to the nested Hyper it only saves the first link and tries to replace it with the last link you added while emptying the other links. It throws an error when the types are different, as well.

- When you've added a nested link the "add a link" stops working in the parent Hyper field. And for Entry types the "choose" button stops working. Saving fixes the button in the nested Hyper but not in the parent.

- If you've deleted a nested link, saving will bring it back.

- Also, when you've added multiple parent links and try to add multiple nested links to each parent, it fails. This might be similar to the first issue but it seems to be different. Instead of replacing the first link, it will empty the first link.

I've recorded the issues which, hopefully, explains it a bit better:

- https://share.cleanshot.com/Z8gJg0lllPvN1pT6Gtnj
- https://share.cleanshot.com/NsHRthgYS2zD2Y95w2Dl

I've also tested Hyper within a Super Table within a Hyper field to create a link column structure and that seems to be working fine. For example:

- https://share.cleanshot.com/4gMtgHDmwHsgb7hS9MNR

### Steps to reproduce

1. Nest Hyper fields
2. Add link to parent Hyper field
3. Add link to nested Hyper field
4. Add a second link to nested Hyper field
5. Save

### Craft CMS version

4.4.13

### Plugin version

1.1.7

### Multi-site?

Yes

### Additional context

There were no migrations from Typed Link Field or other plugins. The Hyper fields were added as brand new fields for testing purposes.

**Comment by stevendierick** [comment]
Bump. Any news on this?

I am now also having the same issue when nesting Hyper within a Super Table (within Hyper to work around this issue). No errors or whatsoever. It won't delete the Super Table row, not even a Hyper link inside it.

Craft CMS version
4.4.15

Plugin version
1.1.9

**Comment by engram-design** [comment]
Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.9"`

**Comment by engram-design** [comment]
Updated in [1.1.10](https://github.com/verbb/hyper/releases/tag/1.1.10)

**Comment by stevendierick** [comment]
We're still having issues when nesting Hyper fields using the same conditions as my original post. Nesting Hyper in Hyper, but also Hyper (with multiple links) in Super Table (in Hyper) for grouping. Deleting a nested Hyper item will bring it back, sometimes it will replace the deleted item with an existing item.

Craft CMS version
4.5

Plugin version
1.1.11

**Comment by engram-design** [comment]
> When you add a link to a nested Hyper then only the first link will work. When you add a second, third, fourth, etc. link to the nested Hyper it only saves the first link and tries to replace it with the last link you added while emptying the other links. It throws an error when the types are different, as well.

Can't seem to replicate this one, sorry. Each new instance of a (nested) Hyper field I'm able to select entries. https://share.cleanshot.com/H8Qr4nJF

> When you've added a nested link the "add a link" stops working in the parent Hyper field. And for Entry types the "choose" button stops working. Saving fixes the button in the nested Hyper but not in the parent.

Can confirm this is now fixed, as I'd missed something last time.

> If you've deleted a nested link, saving will bring it back.
Can't replicate this either, sorry. https://share.cleanshot.com/Cgb9JQmf

**Comment by stevendierick** [comment]
Strange that it seems to be fixed on your end. I've tested `dev-craft-4` on an existing site and on a clean install, and still have nesting issues on both.

I've created 3 tests and recorded them:

1) Hyper with a nested Hyper:
   https://share.cleanshot.com/PsSV3DPD5rkVJVnrg2SZ

2) Super Table with a nested Hyper:
   https://share.cleanshot.com/DT7wpYqvj2VYykwH3P7x

3) Hyper with a nested Super Table which also has a nested Hyper:
   https://share.cleanshot.com/YMvZNtpqQNftPNvjMBNM

As you can see nesting doesn't work correctly in Test 1 and 3. It replaces deleted links, it re-adds them, etc. Also, there seems to be a visual bug when dragging in a nested Hyper.

Test 2 with Super Table seems to be working just fine, which seems logical as we're not exactly nesting Hyper within Hyper but creating a Hyper field inside Super Table.

But in Test 3 where we nest the Super Table (which has a Hyper field) in another Hyper field... it's the same story as Test 1. It evens duplicates or re-adds a deleted Super Table row.

Also tested it on `1.1.11` after testing on `dev-craft-4` with the same results.

Let me know if you need more info or if I can help out in any other way!

Craft CMS version:
4.5.3

Plugin version:
dev-craft-4

**Comment by engram-design** [comment]
Ah, so your fields are in the slideout - that makes a difference. Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.10"`

**Comment by stevendierick** [comment]
Yes, can confirm it works now. Thanks!

**Comment by engram-design** [comment]
Fixed in [1.1.11](https://github.com/verbb/hyper/releases/tag/1.1.11)
