### ISSUE TITLE
Migrating LinkIt fields within Super Table seems to fail

### ISSUE THREAD

**Issue by litzinger** [verbb/hyper#75]
### Describe the bug

Prior to migrating the Matrix field looks like this:

<img width="2145" alt="Screenshot 2023-06-29 at 3 34 49 PM" src="https://github.com/verbb/hyper/assets/53965/1ed6398e-5348-4df5-9aa6-1d5e113dc4bb">

When running `./craft hyper/migrate/linkit-field` it appears to migrate all the field successfully, then hits this one field and throws an exception and I'm unsure why. If I run the command again, it says `Finished Migration` with no errors.

```
Preparing to migrate field “linkit” (740415dc-9f75-426e-a187-c1017f10a776).
    > Field “linkit” migrated.

Preparing to migrate field “sectorLink” (5595c127-0e34-4ac1-85ef-3b964112ecac).
    > Field “sectorLink” migrated.

Re-saving field “ctaLink”.
    > Field “ctaLink” migration finalised.

Re-saving field “ctaLink”.
Exception: {"linkTypes":["Correct the above errors."]} (/my_project/vendor/verbb/hyper/src/migrations/PluginFieldMigration.php:55)
#0 /my_project/vendor/craftcms/cms/src/db/Migration.php(49): verbb\hyper\migrations\PluginFieldMigration->safeUp()
#1 /my_project/vendor/verbb/hyper/src/console/controllers/MigrateController.php(66): craft\db\Migration->up()
#2 /my_project/vendor/verbb/hyper/src/console/controllers/MigrateController.php(24): verbb\hyper\console\controllers\MigrateController->_migrate('verbb\\hyper\\mig...')
#3 [internal function]: verbb\hyper\console\controllers\MigrateController->actionLinkitField()
```

Then the Matrix field looks like this. What is odd is that the URL field seems to repeat and selecting one of them selects all of them. Is this intended behavior?

<img width="1292" alt="Screenshot 2023-06-30 at 9 05 57 AM" src="https://github.com/verbb/hyper/assets/53965/2513f199-8e24-4dfb-b96e-f9077d2012f8">

If I change no settings and save the Matrix field I then get this error:

<img width="965" alt="Screenshot 2023-06-30 at 9 08 46 AM" src="https://github.com/verbb/hyper/assets/53965/427acd4d-667e-48a1-9c03-df666860ffea">

### Steps to reproduce

I'm not sure how to write steps to re-produce. I'm following the guide and running the commands in the expected order. The issue seems to stem from the following structure: Matrix > Super Table > LinkIt field

### Craft CMS version

4.4.14

### Plugin version

1.1.8

### Multi-site?

Yes

### Additional context

PHP 8.1.19

**Comment by engram-design** [comment]
I can't seem to replicate that error (what sort of field is `ctaLink`? Is that in a Matrix or Super Table field?).

However, yes there's 100% an issue with the multiple URL link types. These are actually because it's trying to translate the social media link types to URL as well. I've updated this for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.1.8"`

**Comment by litzinger** [comment]
`ctaLink` is actually the old LinkIt field, and after the migration it's a Hyper field that is inside of a Matrix field.

Migrations appeared to execute successfully and everything was green, then I went into the CP and tried to re-save the Matrix field and got this error again: `Typed property craft\fields\Matrix::$contentTable must not be accessed before initialization`

Before saving the field it didn't have the rendering issue with multiple "URL" fields as shown in the original screenshots.

I did see this error again though:

```
Re-saving field “ctaLink”.
Exception: {"linkTypes":["Correct the above errors."]}
```

**Comment by engram-design** [comment]
So after thinking through this a bit more, I _think_ my fixes should address this, as the error related to the link types is something that I've fixed. Very interesting to see that Matrix contentTable error, I'll look into it...

**Comment by engram-design** [comment]
Updated in [1.1.9](https://github.com/verbb/hyper/releases/tag/1.1.9)

**Comment by litzinger** [comment]
Sorry to bring this back from the dead, but using the new version I'm still getting the same reported PHP errors. The migration _seems_ to work better though.

As for the matrix contentTable error, I just got the same error in another non-Craft project when adding a Trait to a class. In the trait I had to set the default property value to null and use a nullable type hint:

`protected ?Request $request = null;`

Since this error is happening in a core Yii file I'm not sure there is much you can do about that, but it might provide some helpful info? This is what I found to correct my error. https://stackoverflow.com/questions/59265625/why-i-am-suddenly-getting-a-typed-property-must-not-be-accessed-before-initiali

**Comment by engram-design** [comment]
Yeah, I've seen that error crop up once or twice, and it'll certainly be a Craft issue with the `Matrix::$contentTable`. I've yet to figure out how to reproduce it though.
